-- CREATE TABLE IF NOT EXISTS customers (id INT PRIMARY KEY, name VARCHAR(20));
CREATE DATABASE IF NOT EXISTS smartpark;
use smartpark;
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username CHAR(20) NOT NULL,
  password CHAR(128) NOT NULL,
  salt char(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS transactions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userid INT NOT NULL,
  spot INT NOT NULL,
  reserve_time DATETIME NOT NULL,
  reserve_length INT NOT NULL,
  FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE
);
